"""empty message

Revision ID: 07a885af1e04
Revises: 45cb3a443e32
Create Date: 2019-04-01 15:57:24.921346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a885af1e04'
down_revision = '45cb3a443e32'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_list_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_list_type')),
    sa.UniqueConstraint('key')
    )
    op.create_table('custom_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('list_type_key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['list_type_key'], ['custom_list_type.key'], name=op.f('fk_custom_list_list_type_key_custom_list_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_list')),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_list')
    op.drop_table('custom_list_type')
    # ### end Alembic commands ###


def upgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

