"""empty message

Revision ID: 19b9df88f4ee
Revises: 76a3a8420842
Create Date: 2019-05-11 18:54:34.898769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b9df88f4ee'
down_revision = '76a3a8420842'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_session')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_profile_proxy_id_proxy'), 'proxy', ['proxy_id'], ['id'])

    with op.batch_alter_table('proxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.drop_constraint('fk_proxy_profile_id_profile', type_='foreignkey')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_proxy_profile_id_profile', 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_profile_proxy_id_proxy'), type_='foreignkey')
        batch_op.drop_column('proxy_id')

    op.create_table('_alembic_tmp_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('start_datetime', sa.DATETIME(), nullable=True),
    sa.Column('end_datetime', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.CheckConstraint('is_system IN (0, 1)'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='fk_session_profile_id_profile'),
    sa.PrimaryKeyConstraint('id', name='pk_session'),
    sa.UniqueConstraint('key', name='uq_session_key')
    )
    # ### end Alembic commands ###


def upgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

