"""empty message

Revision ID: 45cb3a443e32
Revises:
Create Date: 2019-04-01 01:28:41.636689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cb3a443e32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_unique_constraint("ck_session_key", ['key'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(ck_session_key, type_='unique')

    # ### end Alembic commands ###


def upgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

