"""empty message

Revision ID: 76a3a8420842
Revises: 07a885af1e04
Create Date: 2019-04-13 00:13:16.325190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a3a8420842'
down_revision = '07a885af1e04'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_unique_constraint('ui_profile_username', ['username'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('ui_profile_username', type_='unique')

    # ### end Alembic commands ###


def upgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_instapy():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

