; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "_variables.iss"

#define VersionSuffix "-32bit"
#define AppVerName AppVerName + VersionSuffix
#define OutputBaseFilename OutputBaseFilename + VersionSuffix
#define PythonInstallerFileName "python-3.6.8.exe"
